Fix LTTng-tools builds for versions prior to 2.8 when disabling UST
eepp/vlttng pull request #2
Opened 2016-10-28 17:01 UTC by frdeso

2016-10-28 17:31 UTC, eepp requested changes
Almost there!

2016-10-28 17:31 UTC, eepp commented on vlttng/venv.py
> +            add_args += ' --disable-lttng-ust'
Why not:

    add_args = '--without-lttng-ust --disable-lttng-ust'

Also, the `--disable-lttng-ust` option (and `--enable-lttng-ust=no` I guess) should be detected in line 550 above for the warning message. At this point I would add all those strings to a list and for each of them check if its in `project.configure` (and generate that part of the warning message with `'/'.join(the_list)`).

2016-10-28 20:11 UTC, frdeso commented
see new version of the patch

2016-10-28 20:22 UTC, eepp requested changes

2016-10-28 20:22 UTC, eepp commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
'/'.join(ust_config)

2016-10-28 20:22 UTC, eepp commented on vlttng/venv.py
> +        for ust_config in ['--with-lttng-ust-prefix', '--without-lttng-ust', '--disable-lttng-ust']:
Name this list, add `--enable-lttng-ust=no`.

2016-10-28 20:22 UTC, eepp commented on vlttng/venv.py
> -        if '--with-lttng-ust-prefix' in project.configure or '--without-lttng-ust' in project.configure:
Use the named list here:

    for opt in lttng_ust_opts:
        if opt in project.configure:
            # ...

2016-10-28 21:47 UTC, frdeso commented on vlttng/venv.py
> +        for ust_config in ['--with-lttng-ust-prefix', '--without-lttng-ust', '--disable-lttng-ust']:
Should I include `--enable-lttng-ust=yes` as well?

2016-10-28 21:49 UTC, frdeso commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
Do you mean `'/'.join(lttng_ust_opts)`?

2016-10-28 21:59 UTC, eepp commented on vlttng/venv.py
> +        for ust_config in ['--with-lttng-ust-prefix', '--without-lttng-ust', '--disable-lttng-ust']:
Yes, in fact, just include `--enable-lttng-ust`.

2016-10-28 22:00 UTC, eepp commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
Yes.

2016-10-29 23:09 UTC, eepp commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
You will need to rebase this BTW, there has been some changes in this file.

2016-10-31 17:55 UTC, frdeso commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
using `join()` the entire list will be printed for each `lttng_ust_ops` present in the configure options.
If I have both `--with-lttng-ust-prefix`  and `--enable-lttng-ust=yes`, the same warning will be printed twice.
If that's what we want, we should break after the first warning.

2016-10-31 20:11 UTC, eepp commented on vlttng/venv.py
> +                msg = 'I would not pass the '+ust_config+' configure option if I were you: they are handled by vlttng'
Yes you're right, no join then.

Also, prefer using a tuple than a list for `lttng_ust_opts`.

2016-10-31 21:54 UTC, frdeso commented
see new version of the patch

2016-11-01 01:58 UTC, closed without merging